/* Generated by lab_site/scripts/inject-nexus-env.js — do not hand-edit in CI */
(function () {
    "use strict";
    if (typeof window === "undefined") return;
    var k = "";
    var b = "";
    var c = "";
    var d = "";
    if (k) window.NEXUS_PUBLISHABLE_KEY = k;
    if (b) window.NEXUS_API_BASE = b;
    if (c) window.NEXUS_COLLECT_BASE = c;
    if (d) window.NEXUS_DASH_API = d;
})();
